export type ChapterId = 'research' | 'mrna';
export type ScorePacket = { version: 1; chapter: ChapterId; runId: string; completedAt: string; marks: string; recordType?: 'reference' };
export type ScoreStats = { score: number; firstCorrectCount: number; correctedCount: number; hintedCount: number; totalQuestions: number };
export type PublicAuthor = { login: string; nickname: string; submittedAt: string; issueNumber: number; issueUrl: string };
export type LeaderboardEntry = PublicAuthor & ScoreStats & { rank: number; completedAt: string; recordType?: 'reference' };
export type CommunityComment = PublicAuthor & { body: string; rating: number | null };
export type ChapterCommunity = { entries: LeaderboardEntry[]; totalPlayers: number; comments: CommunityComment[] };
export type CommunitySnapshot = { version: 1; updatedAt: string; repository: string; source: 'github-issues'; selfReported: true; chapters: Record<ChapterId, ChapterCommunity> };
export type Draft = { url: string; body: string; copyRequired: boolean };
export type DraftFields = { nickname?: string; comment?: string; rating?: number | null };
export type Submission = { app: 'socrates-question'; version: 1; kind: 'score' | 'comment'; chapter: ChapterId; nickname: string; comment: string; rating: number | null; packet?: ScorePacket };
export const REPOSITORY: 'yaoyuzhang1/socrates-question';
export const SNAPSHOT_URL: string;
export const QUESTION_COUNTS: Readonly<Record<ChapterId, number>>;
export const CHAPTER_NAMES: Readonly<Record<ChapterId, string>>;
export function scoreMarks(chapter: unknown, marks: unknown): ScoreStats | null;
export function parsePacket(input: unknown): ScorePacket | null;
export function buildScoreDraftUrl(packet: unknown, fields?: DraftFields): Draft;
export function buildCommentDraftUrl(fields: DraftFields & { chapter: ChapterId }): Draft;
export function parseIssueSubmission(body: unknown): Submission | null;
export function emptyCommunitySnapshot(updatedAt?: string): CommunitySnapshot;
export function buildCommunitySnapshot(issues: unknown[], updatedAt?: string): CommunitySnapshot;
export function validateCommunitySnapshot(value: unknown): CommunitySnapshot | null;
export function sameCommunityData(left: unknown, right: unknown): boolean;
